version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    command: bash -c "alembic upgrade head && uvicorn api:app --host 0.0.0.0 --port 8080 --reload"
    networks:
      - backend

  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

networks:
  backend:
    driver: bridge